name: Deploy to Deta

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Provide requirements (for deta)
        run: |
          python -m pip install pip-tools>=6.12
          cd draw_ascii
          pip-compile --output-file requirements.txt ../pyproject.toml
      
      - name: Deploy to deta
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: draw_ascii 
          deta-project-dir: draw_ascii